# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import PyQt5, openpyxl, jmespath
import numpy as np
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import Qt

wbname = 'budgetmanager.xlsx'

class Wydatek:
    def __init__(self, data,kategoria,kwota,opis):
        self.data = data
        self.kategoria = kategoria
        self.kwota = kwota
        self.opis = opis
        pass

class BudgetManager:
    def __init__(self):
        self.wydatki = []
        wb = openpyxl.load_workbook(wbname)
        ws = wb.active
        for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
            data = row[0].value
            kategoria = row[1].value
            kwota = row[2].value
            opis = row[3].value
            self.wydatki.append(Wydatek(data,kategoria,kwota,opis))
        wb.save(wbname)
        pass

    def dodaj_wydatek(self, Wydatek):
        data = Wydatek.data
        kategoria = Wydatek.kategoria
        kwota = Wydatek.kwota
        opis = Wydatek.opis
        self.wydatki.append(Wydatek(data,kategoria,kwota,opis))
        pass

    def oblicz_sume_kategorii(self, kategoriaSzukana):
        suma = 0
        for konkretnywydatek in self.wydatki:
            if konkretnywydatek.kategoria == kategoriaSzukana:
                suma += int(konkretnywydatek.kwota)
        return suma

    def wczytaj_z_excela(self, nazwaexcela):
        self.wydatki = []
        wb = openpyxl.load_workbook(nazwaexcela)
        ws = wb.active
        for row in ws.iter_rows(min_row=1, max_row=ws.max_row):
            data = row[0].value
            kategoria = row[1].value
            kwota = row[2].value
            opis = row[3].value
            self.wydatki.append(Wydatek(data, kategoria, kwota, opis))
        wb.save(nazwaexcela)
        pass

    def czysc_dane(self):
        self.wydatki = []
        pass

class TableModel(QtCore.QAbstractTableModel):
    def __init__(self, data):
        super().__init__()
        self._data = data

    def data(self, index, role):
        if role == Qt.DisplayRole:
            # See below for the nested-list data structure.
            # .row() indexes into the outer list,
            # .column() indexes into the sub-list
            return self._data[index.row()][index.column()]

    def rowCount(self, index):
        # The length of the outer list.
        return len(self._data)

    def columnCount(self, index):
        # The following takes the first sub-list, and returns
        # the length (only works if all rows are an equal length)
        return len(self._data[0])

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 0, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 40, 101, 23))
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(40, 70, 331, 351))
        self.tableView.setObjectName("tableView")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 540, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 420, 91, 16))
        self.label_2.setObjectName("label_2")

        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(30, 460, 110, 22))
        self.dateEdit.setObjectName("dateEdit")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 440, 47, 13))
        self.label_3.setObjectName("label_3")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(150, 460, 69, 22))
        self.comboBox.setObjectName("comboBox")

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 440, 47, 13))
        self.label_4.setObjectName("label_4")

        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(230, 440, 47, 13))
        self.label_5.setObjectName("label_5")

        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(230, 460, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 490, 47, 13))
        self.label_6.setObjectName("label_6")

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 510, 261, 20))
        self.lineEdit.setObjectName("lineEdit")

        self.columnView = QtWidgets.QColumnView(self.centralwidget)
        self.columnView.setGeometry(QtCore.QRect(410, 100, 371, 321))
        self.columnView.setObjectName("columnView")

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(510, 70, 181, 16))
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 440, 111, 16))
        self.label_8.setObjectName("label_8")

        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(550, 460, 69, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(530, 500, 31, 16))
        self.label_9.setObjectName("label_9")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(570, 500, 47, 13))
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(640, 500, 16, 16))
        self.label_11.setObjectName("label_11")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Aplikacja do zarządzania budżetem"))
        self.pushButton.setText(_translate("MainWindow", "Wczytaj Excel"))
        self.pushButton_2.setText(_translate("MainWindow", "Dodaj wiersz"))
        self.label_2.setText(_translate("MainWindow", "Dodawanie wiersza"))
        self.label_3.setText(_translate("MainWindow", "Data"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Jedzenie"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Rozrywka"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Rachunki"))
        self.label_4.setText(_translate("MainWindow", "Kategoria"))
        self.label_5.setText(_translate("MainWindow", "Kwota"))
        self.label_6.setText(_translate("MainWindow", "Opis"))
        self.label_7.setText(_translate("MainWindow", "Udział kategorii wydatków w całości"))
        self.label_8.setText(_translate("MainWindow", "Oblicz sumę kategorii"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Jedzenie"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Rozrywka"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Rachunki"))
        self.label_9.setText(_translate("MainWindow", "Suma:"))
        self.label_10.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "zł"))

class BudgetApp:
    def __init__(self, window):
        self.window = window
        self.manager = BudgetManager()

        self.window.pushButton.clicked.connect(self.wczytajExcel)
        self.window.pushButton_2.clicked.connect(self.dodajWiersz)

    def wczytajExcel(self):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(self.window, "QFileDialog.getOpenFileName()", "","All Files (*);;Excel Files (*.xlsx)", options=options)
        if fileName:

            self.manager.wczytaj_z_excela(fileName)
            data = []
            wydatki = self.manager.wydatki
            for wiersz in wydatki:
                data.append([wiersz.data, wiersz.kategoria, wiersz.kwota, wiersz.opis])
            self.model = TableModel(data)
            self.window.tableView.setModel(self.model)
    def dodajWiersz(self):
        data = str(self.window.dateEdit.date().toPyDate())
        kategoria = str(self.window.comboBox.currentText())
        kwota = str(self.window.doubleSpinBox.value())
        opis = str(self.window.lineEdit.text())
        wydatek = Wydatek(data, kategoria, kwota, opis)
        self.manager.dodaj_wydatek(wydatek)




class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)


app = QtWidgets.QApplication([])
window = MainWindow()
window.show()
controller = BudgetApp(window)
app.exec_()

# data = self.window.dateEdit.date()
# kategoria = self.window.comboBox.currentText()
# kwota = str(self.window.doubleSpinBox.value())
# opis = self.window.QLineEdit.text()